name: build-windows
on:
  workflow_dispatch: null

jobs:
  build-windows:
    name: Build StemRoller for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run download-third-party-apps
      - run: npm run setup:roformer
      - run: npm run setup:multistem
      - run: npm test
      - run: npm run build:win
      - uses: actions/upload-artifact@v4
        with:
          name: stemroller-roformer-windows
          path: dist/win-unpacked
          retention-days: 7
          compression-level: 0
